### ISSUE TITLE
Submit event doesn't trigger async inputs validations

### ISSUE THREAD

**Issue by eseceve** [iusehooks/usetheform#32]
# Problem
Submit event doesn't trigger async validations of each input

> I don't know if this its a feature or bug 

## Current Behavior
Just only runs sync validations of each input

## Expected Behavior
Run sync and async validations of each input

## Demo
https://codesandbox.io/s/usetheform-asyncvalidators-submit-blbto

**Comment by iusehooks** [comment]
Hi @eseceve,

In your example you applied 2 validators one is Sync and one is Async.

Async validators run only if all the Sync validations have passed, no otherwise.

Reasons why is this way is to avoid calling async functions if your form is not valid.

Hope it helped. 

```jsx
 <TextField
          label="Standard"
          name="standard"
          touched
          validators={[required]}
        />
        <TextAsyncField
          label="Filled"
          variant="filled"
          name="filled"
          validator={asyncRequired}
        />
```

**Comment by eseceve** [comment]
> Async validators run only if all the Sync validations have passed, no otherwise.
> 
> Reasons why is this way is to avoid calling async functions if your form is not valid.

The problem that I see with this approach it's I can't use only async validations in my forms. I'll need to write an asyncValidation for the form too, not just for each input.

**Comment by eseceve** [comment]
I would like to run async validations of each input on submit if there aren't validated yet

**Comment by iusehooks** [comment]
Would you please describe me a case in which you need to run an async validator function if a sync fails? Thanks

**Comment by eseceve** [comment]
I don't know why I had assumed that I couldn't use `validators` and` asyncValidator` at the same time.
I already understood how to do what I need.

**Comment by iusehooks** [comment]
Hi @eseceve,
 
You can apply both validations sync and async on the same input or different inputs. 

Priority is given to sync, so if one sync functions fails the async validators will not be excuted.

If you like usetheform a github star will be appriciated.

Thanks.
